### ISSUE TITLE
Segmentation Fault at end of "The Stack" chapter

### ISSUE THREAD

**Issue by IslandUsurper** [cfsamson/book-green-threads-explained#4]
The Bonus Material section has code that outputs the (bigger) stack into files BEFORE.txt and AFTER.txt. However, when I try running it, I get a seg fault sometime after BEFORE.txt is written. AFTER.txt isn't written, so I'm guessing it's somewhere in the context switch. I'm not very experienced with unsafe code, assembly, or anything this low-level, so I don't have any more insight than that, I'm afraid.

**Comment by IslandUsurper** [comment]
Ah, some details:

    rustc --version: 1.36.0-nightly (e305df184 2019-04-24)
    toolchain: nightly-x86_64-unknown-linux-gnu

**Comment by cfsamson** [comment]
Ah, I think I know what's up. This is one of the issues writing for three targets and only having two of them (I'm testing Linux on the Playground but that won't work for outputting files.

Can you please check for me if this works?
(only changed is that I removed the #[naked] attribute on the `hello()` function).
```rust
#![feature(asm)]
#![feature(naked_functions)]
use std::io::Write;

const SSIZE: isize = 1024;
static mut S_PTR: *const u8 = 0 as *const u8;

#[derive(Debug, Default)]
#[repr(C)]
struct ThreadContext {
    rsp: u64,
    r15: u64,
    r14: u64,
    r13: u64,
    r12: u64,
    rbx: u64,
    rbp: u64,
}

fn print_stack(filename: &str) {
    let mut f = std::fs::File::create(filename).unwrap();
    unsafe {
        for i in (0..SSIZE).rev() {
            writeln!(
                f,
                "mem: {}, val: {}",
                S_PTR.offset(i as isize) as usize,
                *S_PTR.offset(i as isize)
            );
        }
    }
}


fn hello() {
    println!("I LOVE WAKING UP ON A NEW STACK!");
    print_stack("AFTER.txt");

    loop {}
}


unsafe fn gt_switch(new: *const ThreadContext) {
    asm!("
        mov     0x00($0), %rsp
        ret
       "
    :
    : "r"(new)
    :
    : "alignstack"
    );
}

fn main() {
    let mut ctx = ThreadContext::default();
    let mut stack = vec![0_u8; SSIZE as usize];
    let stack_ptr = stack.as_mut_ptr();

    unsafe {
        S_PTR = stack_ptr;
        std::ptr::write(stack_ptr.offset(SSIZE - 16) as *mut u64, hello as u64);
        print_stack("BEFORE.txt");
        ctx.rsp = stack_ptr.offset(SSIZE - 16) as u64;
        gt_switch(&mut ctx);
    }
}

```

**Comment by IslandUsurper** [comment]
Yes, that does work. I haven't heard of the naked_functions feature, so I guess I'll go read up on that.

**Comment by cfsamson** [comment]
Perfect. I write about it in the next chapter, so you can check there first :)

**Comment by IslandUsurper** [comment]
Great. Thanks.

**Comment by cfsamson** [comment]
Book is now updated. Need to test this on OSX though. Tested on Linux and Windows.
